name: release
on:
  push:
    # Enable when testing release infrastructure on a branch + set a GA_VERSION a few lines below
    # branches:
    # -  release-twiddling
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
